import Head from "next/head";
import Feed from "../components/Feed";
import Sidebar from "../components/Sidebar";
import Widgets from "../components/Widgets";

export default function Home({ news, randomUser }) {
  return (
    <div>
      <Head>
        <title>Bird App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen  mx-auto">
        <Sidebar />
        <Feed />
        <Widgets
          newsResult={news.articles}
          randomUserResults={randomUser.results}
        />
      </main>
    </div>
  );
}

// https://saurav.tech/NewsAPI/top-headlines/category/business/us.json
// https://randomuser.me/api/?results=30&inc=name,login,picture
export async function getServerSideProps() {
  const newsResult = await fetch(
    "https://saurav.tech/NewsAPI/top-headlines/category/business/us.json"
  );
  const news = await newsResult.json();

  //who to follow
  const randomUserResults = await fetch(
    "https://randomuser.me/api/?results=30&inc=name,login,picture"
  );
  const randomUser = await randomUserResults.json();

  return {
    props: {
      news,
      randomUser,
    },
  };
}
